# Copyright (c) 2026, Upande LTD and contributors
# For license information, please see license.txt

import frappe
from frappe.desk.form.assign_to import add as add_assignment
from frappe.tests import IntegrationTestCase
from frappe.utils import add_to_date, now_datetime, today

from upande_dev_tools.api.requests import (
	accept_request,
	create_request,
	get_assignable_users,
	get_customer_workload,
	get_developer_backlog,
	get_my_day,
	get_my_requests,
	get_review_queue,
	get_upcoming_meetings,
	promote_to_task,
	triage_request,
)


class IntegrationTestRequestsApi(IntegrationTestCase):
	def test_task_has_request_custom_fields(self) -> None:
		meta = frappe.get_meta("Task")
		self.assertTrue(meta.has_field("custom_request"))
		self.assertTrue(meta.has_field("custom_planned_for"))

	def _make_user(self, email: str, roles: list[str]) -> str:
		if not frappe.db.exists("User", email):
			frappe.get_doc(
				{"doctype": "User", "email": email, "first_name": "Test", "send_welcome_email": 0}
			).insert(ignore_permissions=True)
		user = frappe.get_doc("User", email)
		if roles:
			user.add_roles(*roles)
		return email

	def test_create_request_rejects_note_from_non_dev(self) -> None:
		pm = self._make_user("pm-create@example.test", ["Projects Manager"])
		frappe.set_user(pm)
		try:
			with self.assertRaises(frappe.ValidationError):
				create_request(title="sneaky note", request_type="Note")
		finally:
			frappe.set_user("Administrator")

	def test_get_my_requests_scopes_to_caller(self) -> None:
		dev = self._make_user("dev-scope@example.test", ["Dev Team"])
		other = self._make_user("other-scope@example.test", ["Dev Team"])

		try:
			frappe.set_user(dev)
			created = create_request(title="My own request", request_type="Bug")
			frappe.set_user(other)
			create_request(title="Someone else's request", request_type="Bug")

			frappe.set_user(dev)
			mine = get_my_requests()
		finally:
			frappe.set_user("Administrator")
		self.assertEqual([r["name"] for r in mine], [created["name"]])

	def test_get_review_queue_requires_reviewer_role(self) -> None:
		outsider = self._make_user("outsider-queue@example.test", [])
		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_review_queue()
		finally:
			frappe.set_user("Administrator")

	def _make_project(self) -> str:
		name = "Requests Phase 1 Test Project"
		# Look up by project_name, not docname (autogenerated) - callable more than once
		# per test transaction.
		existing = frappe.db.exists("Project", {"project_name": name})
		if existing:
			return existing
		# Reuse whatever Company already exists rather than creating one (which triggers
		# HRMS regional setup side effects).
		company = frappe.db.get_value("Company", {}, "name")
		if not company:
			self.skipTest("No Company exists on this site to attach a test Project to.")
		return (
			frappe.get_doc({"doctype": "Project", "project_name": name, "company": company})
			.insert(ignore_permissions=True)
			.name
		)

	def test_triage_and_promote_normal_request(self) -> None:
		# Also needs "Projects User" - create_request checks read permission on the project.
		dev = self._make_user("dev-triage@example.test", ["Dev Team", "Projects User"])
		pm = self._make_user("pm-triage@example.test", ["Projects Manager"])
		project = self._make_project()

		frappe.set_user(dev)
		created = create_request(title="Add CSV export", request_type="Feature", project=project)

		frappe.set_user(pm)
		triage_request(created["name"], "Approve", priority="High")
		promote_to_task(created["name"])
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Scheduled")
		self.assertTrue(doc.linked_task)

	def test_promote_to_task_lets_dev_team_self_promote_a_note(self) -> None:
		dev = self._make_user("dev-note-promote@example.test", ["Dev Team"])
		frappe.set_user(dev)
		created = create_request(title="Remember to refactor this", request_type="Note")
		promote_to_task(created["name"])
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Scheduled")

	def test_dev_team_can_start_and_complete_scheduled_request(self) -> None:
		dev = self._make_user("dev-lifecycle@example.test", ["Dev Team"])
		pm = self._make_user("pm-lifecycle@example.test", ["Projects Manager"])
		project = self._make_project()

		frappe.set_user(pm)
		created = create_request(title="Small fix", request_type="Bug", project=project)
		triage_request(created["name"], "Approve", priority="Low")
		promote_to_task(created["name"])

		frappe.set_user(dev)
		triage_request(created["name"], "Start Work")
		triage_request(created["name"], "Complete")
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Completed")

	def test_get_backlog_board_returns_requests_for_project(self) -> None:
		project = self._make_project()
		created = create_request(title="Board item", request_type="Feature", project=project)

		board = get_backlog_board(project=project)
		self.assertIn(created["name"], [r["name"] for r in board["requests"]])

	def test_get_backlog_board_shows_requester_and_assignee(self) -> None:
		# Needs "Projects User" too - create_request checks read permission on the project.
		dev = self._make_user("dev-board-assignee@example.test", ["Dev Team", "Projects User"])
		project = self._make_project()

		frappe.set_user(dev)
		try:
			created = create_request(title="Needs an owner shown", request_type="Bug", project=project)
		finally:
			frappe.set_user("Administrator")

		task = frappe.get_doc({"doctype": "Task", "subject": "Board task with an owner", "project": project})
		task.flags.ignore_recursion_check = True
		task.insert(ignore_permissions=True)
		add_assignment({"doctype": "Task", "name": task.name, "assign_to": [dev]})

		board = get_backlog_board(project=project)

		request_row = next(r for r in board["requests"] if r["name"] == created["name"])
		self.assertEqual(request_row["requested_by"], frappe.db.get_value("User", dev, "full_name"))

		task_row = next(t for t in board["tasks"] if t["name"] == task.name)
		self.assertEqual(task_row["assigned_to"], [frappe.db.get_value("User", dev, "full_name")])

	def test_get_backlog_board_denies_outsider_without_project(self) -> None:
		outsider = self._make_user("outsider-board@example.test", [])
		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_backlog_board()
		finally:
			frappe.set_user("Administrator")

	def test_get_upcoming_meetings_by_project(self) -> None:
		project = self._make_project()
		event = frappe.get_doc(
			{
				"doctype": "Event",
				"subject": "Sprint planning",
				"event_type": "Private",
				"starts_on": add_to_date(now_datetime(), hours=2),
				"ends_on": add_to_date(now_datetime(), hours=3),
			}
		)
		event.append("links", {"link_doctype": "Project", "link_name": project})
		event.insert(ignore_permissions=True)

		meetings = get_upcoming_meetings(project=project)
		self.assertIn(event.name, [m["name"] for m in meetings])

	def test_get_my_day_returns_assigned_planned_task_and_events(self) -> None:
		dev = self._make_user("dev-myday@example.test", ["Dev Team"])
		project = self._make_project()

		task = frappe.get_doc(
			{
				"doctype": "Task",
				"subject": "Fix login bug",
				"project": project,
				"custom_planned_for": today(),
			}
		)
		task.flags.ignore_recursion_check = True  # see Global Constraints (pypika)
		task.insert(ignore_permissions=True)
		add_assignment({"doctype": "Task", "name": task.name, "assign_to": [dev]})

		event = frappe.get_doc(
			{
				"doctype": "Event",
				"subject": "Standup",
				"event_type": "Private",
				"starts_on": add_to_date(now_datetime(), hours=1),
				"ends_on": add_to_date(now_datetime(), hours=1, minutes=15),
			}
		)
		# Event Participant.reference_doctype/reference_docname are mandatory on this version.
		event.append(
			"event_participants", {"reference_doctype": "User", "reference_docname": dev, "email": dev}
		)
		event.insert(ignore_permissions=True)

		frappe.set_user(dev)
		try:
			day = get_my_day()
		finally:
			frappe.set_user("Administrator")

		self.assertEqual([t["name"] for t in day["tasks"]], [task.name])
		self.assertIn(event.name, [m["name"] for m in day["meetings"]])

	def test_get_my_day_denies_viewing_another_users_day(self) -> None:
		dev = self._make_user("dev-myday-owner@example.test", ["Dev Team"])
		outsider = self._make_user("outsider-myday@example.test", [])

		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_my_day(user=dev)
		finally:
			frappe.set_user("Administrator")

	def test_get_developer_backlog_includes_open_tasks_regardless_of_planned_date(self) -> None:
		dev = self._make_user("dev-backlog-owner@example.test", ["Dev Team"])
		project = self._make_project()

		task = frappe.get_doc(
			{
				"doctype": "Task",
				"subject": "Not planned for today, still open",
				"project": project,
				"status": "Open",
			}
		)
		task.flags.ignore_recursion_check = True
		task.insert(ignore_permissions=True)
		add_assignment({"doctype": "Task", "name": task.name, "assign_to": [dev]})

		done_task = frappe.get_doc(
			{"doctype": "Task", "subject": "Already done", "project": project, "status": "Completed"}
		)
		done_task.flags.ignore_recursion_check = True
		done_task.insert(ignore_permissions=True)
		add_assignment({"doctype": "Task", "name": done_task.name, "assign_to": [dev]})

		frappe.set_user(dev)
		try:
			backlog = get_developer_backlog()
		finally:
			frappe.set_user("Administrator")

		names = [t["name"] for t in backlog]
		self.assertIn(task.name, names)
		self.assertNotIn(done_task.name, names)

	def test_get_developer_backlog_denies_viewing_another_users_backlog(self) -> None:
		dev = self._make_user("dev-backlog-viewee@example.test", ["Dev Team"])
		outsider = self._make_user("outsider-backlog@example.test", [])

		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_developer_backlog(user=dev)
		finally:
			frappe.set_user("Administrator")

	def test_get_customer_workload_permits_a_requester_of_that_project(self) -> None:
		dev = self._make_user("dev-customer-workload@example.test", ["Dev Team", "Projects User"])
		project = self._make_project()

		frappe.set_user(dev)
		create_request(title="Customer workload test", request_type="Bug", project=project)

		task = frappe.get_doc(
			{"doctype": "Task", "subject": "Active work for the customer", "project": project}
		)
		task.flags.ignore_recursion_check = True
		task.insert(ignore_permissions=True)
		add_assignment({"doctype": "Task", "name": task.name, "assign_to": [dev]})

		workload = get_customer_workload(project=project)
		frappe.set_user("Administrator")

		row = next(w for w in workload if w["user"] == dev)
		self.assertGreaterEqual(row["active_tasks"], 1)
		self.assertEqual(row["full_name"], frappe.db.get_value("User", dev, "full_name"))
		self.assertNotIn("exp_end_date", row)

	def test_get_customer_workload_denies_someone_with_no_relationship_to_the_project(self) -> None:
		project = self._make_project()
		outsider = self._make_user("outsider-customer-workload@example.test", [])

		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_customer_workload(project=project)
		finally:
			frappe.set_user("Administrator")

	def test_get_assignable_users_lists_dev_team(self) -> None:
		dev = self._make_user("queue-dev@example.test", ["Dev Team"])
		frappe.set_user("Administrator")
		self.assertIn(dev, [row["name"] for row in get_assignable_users()])

	def test_accept_request_schedules_it_and_assigns_the_task(self) -> None:
		dev = self._make_user("queue-owner@example.test", ["Dev Team"])
		project = self._make_project()
		frappe.set_user("Administrator")
		request = frappe.get_doc(
			{"doctype": "Request", "title": "Needs doing", "request_type": "Feature"}
		).insert(ignore_permissions=True)

		result = accept_request(request.name, project=project, priority="High", assign_to=dev)

		self.assertEqual(result["workflow_state"], "Scheduled")
		self.assertTrue(result["task"])
		owners = frappe.get_all(
			"ToDo",
			filters={"reference_type": "Task", "reference_name": result["task"], "status": "Open"},
			pluck="allocated_to",
		)
		self.assertIn(dev, owners)

	def test_accept_request_refuses_without_a_project(self) -> None:
		request = frappe.get_doc(
			{"doctype": "Request", "title": "No project", "request_type": "Feature"}
		).insert(ignore_permissions=True)
		with self.assertRaises(frappe.ValidationError):
			accept_request(request.name, project="", priority="High")

	def test_accept_request_denies_a_non_reviewer(self) -> None:
		request = frappe.get_doc(
			{"doctype": "Request", "title": "Not yours", "request_type": "Feature"}
		).insert(ignore_permissions=True)
		outsider = self._make_user("queue-outsider@example.test", ["Employee"])
		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				accept_request(request.name, project="X", priority="High")
		finally:
			frappe.set_user("Administrator")
