# Copyright (c) 2026, Upande Limited

import frappe
from frappe.tests import IntegrationTestCase

from upande_dev_tools.api.requests import (
	create_request,
	get_backlog_board,
	get_my_requests,
	get_review_queue,
	promote_to_task,
	triage_request,
)


class IntegrationTestRequestsApi(IntegrationTestCase):
	def test_task_has_request_custom_fields(self) -> None:
		meta = frappe.get_meta("Task")
		self.assertTrue(meta.has_field("custom_request"))
		self.assertTrue(meta.has_field("custom_planned_for"))

	def _make_user(self, email: str, roles: list[str]) -> str:
		if not frappe.db.exists("User", email):
			frappe.get_doc(
				{"doctype": "User", "email": email, "first_name": "Test", "send_welcome_email": 0}
			).insert(ignore_permissions=True)
		user = frappe.get_doc("User", email)
		if roles:
			user.add_roles(*roles)
		return email

	def test_create_request_rejects_note_from_non_dev(self) -> None:
		pm = self._make_user("pm-create@example.test", ["Projects Manager"])
		frappe.set_user(pm)
		try:
			with self.assertRaises(frappe.ValidationError):
				create_request(title="sneaky note", request_type="Note")
		finally:
			frappe.set_user("Administrator")

	def test_get_my_requests_scopes_to_caller(self) -> None:
		dev = self._make_user("dev-scope@example.test", ["Dev Team"])
		other = self._make_user("other-scope@example.test", ["Dev Team"])

		frappe.set_user(dev)
		created = create_request(title="My own request", request_type="Bug")
		frappe.set_user(other)
		create_request(title="Someone else's request", request_type="Bug")

		frappe.set_user(dev)
		try:
			mine = get_my_requests()
		finally:
			frappe.set_user("Administrator")
		self.assertEqual([r["name"] for r in mine], [created["name"]])

	def test_get_review_queue_requires_reviewer_role(self) -> None:
		outsider = self._make_user("outsider-queue@example.test", [])
		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_review_queue()
		finally:
			frappe.set_user("Administrator")

	def _make_project(self) -> str:
		name = "Requests Phase 1 Test Project"
		# Project's docname is autogenerated (naming series), not `project_name`, so look
		# up by the unique `project_name` field rather than by docname — this helper is
		# called from more than one test in this class within a single, uncommitted test
		# transaction, and a docname-based exists() check would never match, causing a
		# duplicate-entry error on the second call.
		existing = frappe.db.exists("Project", {"project_name": name})
		if existing:
			return existing
		# Project.company is mandatory; reuse whatever Company already exists on
		# this site rather than hardcoding one — there is always at least one on
		# a real bench, and creating a new Company triggers HRMS's regional
		# setup side effects, which this test has no reason to exercise.
		company = frappe.db.get_value("Company", {}, "name")
		if not company:
			self.skipTest("No Company exists on this site to attach a test Project to.")
		return (
			frappe.get_doc({"doctype": "Project", "project_name": name, "company": company})
			.insert(ignore_permissions=True)
			.name
		)

	def test_triage_and_promote_normal_request(self) -> None:
		dev = self._make_user("dev-triage@example.test", ["Dev Team"])
		pm = self._make_user("pm-triage@example.test", ["Projects Manager"])
		project = self._make_project()

		frappe.set_user(dev)
		created = create_request(title="Add CSV export", request_type="Feature", project=project)

		frappe.set_user(pm)
		triage_request(created["name"], "Approve", priority="High")
		promote_to_task(created["name"])
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Scheduled")
		self.assertTrue(doc.linked_task)

	def test_promote_to_task_lets_dev_team_self_promote_a_note(self) -> None:
		dev = self._make_user("dev-note-promote@example.test", ["Dev Team"])
		frappe.set_user(dev)
		created = create_request(title="Remember to refactor this", request_type="Note")
		promote_to_task(created["name"])
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Scheduled")

	def test_dev_team_can_start_and_complete_scheduled_request(self) -> None:
		dev = self._make_user("dev-lifecycle@example.test", ["Dev Team"])
		pm = self._make_user("pm-lifecycle@example.test", ["Projects Manager"])
		project = self._make_project()

		frappe.set_user(pm)
		created = create_request(title="Small fix", request_type="Bug", project=project)
		triage_request(created["name"], "Approve", priority="Low")
		promote_to_task(created["name"])

		frappe.set_user(dev)
		triage_request(created["name"], "Start Work")
		triage_request(created["name"], "Complete")
		frappe.set_user("Administrator")

		doc = frappe.get_doc("Request", created["name"])
		self.assertEqual(doc.workflow_state, "Completed")

	def test_get_backlog_board_returns_requests_for_project(self) -> None:
		project = self._make_project()
		created = create_request(title="Board item", request_type="Feature", project=project)

		board = get_backlog_board(project=project)
		self.assertIn(created["name"], [r["name"] for r in board["requests"]])

	def test_get_backlog_board_denies_outsider_without_project(self) -> None:
		outsider = self._make_user("outsider-board@example.test", [])
		frappe.set_user(outsider)
		try:
			with self.assertRaises(frappe.PermissionError):
				get_backlog_board()
		finally:
			frappe.set_user("Administrator")
